### ISSUE TITLE
ofTrueTypeFont returns bad access

### ISSUE THREAD

**Issue by joaodafonseca** [openframeworks/openFrameworks#4383]
Since I port some code to the master version of openframeworks, I randomly/sometimes got the following error, everything was working fine with 0.8.4 version

<img width="1086" alt="screen shot 2015-09-20 at 16 53 19" src="https://cloud.githubusercontent.com/assets/1932216/9981250/5af3c100-5fb8-11e5-8549-cd67e828cc6e.png">

any ideas?

**Comment by arturoc** [comment]
not sure what was going on but that commit should fix it since it doesn't access the array at all. but if you test and is still problematic please post again.

thanks!

**Comment by joaodafonseca** [comment]
Thanks for the update.
Unfortunately still getting the same error, If I comment the FT_Get_Kerning line the code runs, but the text has no anti aliasing!

**Comment by arturoc** [comment]
that's really strange, the kerning has nothing to do with the antialiasing. can you post the values of the variables in that line?

**Comment by joaodafonseca** [comment]
<img width="860" alt="screen shot 2015-09-21 at 22 18 44" src="https://cloud.githubusercontent.com/assets/1932216/10003896/1a3ef65a-60af-11e5-9d77-b253fbdd1d60.png">

**Comment by arturoc** [comment]
not sure why prevC has no value there, i can't reproduce this error, can you post a minimal example that crashes so i can test what's going on?

**Comment by joaodafonseca** [comment]
Hi @arturoc,

I tried to make a minimal version of what I had but can't reproduce the error that way. What I'm doing is creating labels for a bunch of moving objects. Maybe is something with my code. I'll double check, but it's strange that it works with 0.8.4 version or if I comment the FT_Get_Kerning line. What is that line doing exactly btw?

I'll go through my code and let you know...
