### ISSUE TITLE
ofSystemLoadDialog failing on VS2015 on master branch.

### ISSUE THREAD

**Issue by bakercp** [openframeworks/openFrameworks#4464]
`ofSystemLoadDialog` is failing silently on Win 8.1 with VS 2015 on the master branch.

It returns and no selected files or folders and no dialog window appears.

May be related to #3014, though the symptoms are not the same.

**Comment by bilderbuchi** [comment]
ping @openframeworks/windows

**Comment by arturoc** [comment]
mmh, i'm testing this in windows 8.1 and it's working for me fine, both showing the dialog and returning the file name

**Comment by bakercp** [comment]
try this:

```
ofFileDialogResult openFileResult= ofSystemLoadDialog("Select a jpg or png", false, "c:\\"); 
```

**Comment by DomAmato** [comment]
I can confirm on Windows 10 this is also a problem using the above code. investigating

**Comment by bakercp** [comment]
Thanks @DomAmato testing now ...

**Comment by bilderbuchi** [comment]
fixed by #4474

**Comment by bakercp** [comment]
Hi all, sorry to re-open this but I'm still having problems.

Now the path seems to work -- that is -- the dialog opens, but it is returning nothing when a file is selected.  For example:

```c++
    ofFileDialogResult result = ofSystemLoadDialog("Open Project",
                                                   false,
                                                   getUserProjectsPath().toString());

	
	cout << result.fileName << " / " << result.filePath << " / " << result.getName() << " / " << result.getPath() << endl;
```

**Comment by DomAmato** [comment]
Thought I tested it thoroughly, strange since I didn't alter the code that handles the resulting file string and I moved the initialization so that it shouldn't be a null pointer... Back to testing hah  ¯\_(ツ)_/¯

**Comment by DomAmato** [comment]
deleted the pointer for the file name in the last PR... should be fixed now in most recent PR, tried different directory, drives, file types and no errors but curious for other people to give it a test

**Comment by bakercp** [comment]
Fixed by #4476
