### ISSUE TITLE
 setVolume() of ofVideoPlayer overwriten in update() 

### ISSUE THREAD

**Issue by dmelladom** [openframeworks/openFrameworks#4689]
Hi,
v0.8.4 allowed to set the volume during setup() ant its value was kept during all the execution.
In v0.9.0, under mac os x 10.11.2, volume value is reset in update(), this meaning volume is set to 1 every cyce unless it is explicitly set to other value.

**Comment by i-n-g-o** [comment]
Hello.
This should be fixed in the current master by PR #4669 and #4681
related ticket: https://github.com/openframeworks/openFrameworks/issues/3763

**Comment by i-n-g-o** [comment]
you are right, there was an issue, the internal volume should be set even if the player is not ready.
here the PR: https://github.com/openframeworks/openFrameworks/pull/4690

**Comment by kflak** [comment]
Seems this problem is still happening in Linux.

This works for me: 
```void ofApp::update(){

    if ((ofGetElapsedTimef() - startTime) > videoDuration ){
        file = ofApp::getFile();
        videoDuration = ofApp::getVideoDuration();
        startTime = ofGetElapsedTimef();
        movie.load(file);
        ofLog()<<volume<<endl;
        movie.play();
    };

    movie.setVolume(volume);
    movie.update(); 
}
```
This doesn't:
```
void ofApp::update(){

    if ((ofGetElapsedTimef() - startTime) > videoDuration ){
        file = ofApp::getFile();
        videoDuration = ofApp::getVideoDuration();
        startTime = ofGetElapsedTimef();
        movie.load(file);
        movie.setVolume(volume);
        ofLog()<<volume<<endl;
        movie.play();
    };

    movie.update(); 
}
```

Platform: Arch Linux, 
OpenFrameworks version: of_v20200912_linux64gcc6_release

**Comment by Solcany** [comment]
The same issue is still on Mac Os 10.14.6 Mojave and of_v0.11.0_osx_release
