### ISSUE TITLE
Calling ofImage.grabScreen() followed by ofImage.resize() results in distorted colours

### ISSUE THREAD

**Issue by jberghold** [openframeworks/openFrameworks#6528]
**Steps to reproduce**:
1. Call ofImage.grabScreen() on a portion of the app window
2. Call ofImage.resize() to enlarge or shrink the image just captured
3. Call ofImage.save()

**Expected result**:
Image should save with the correct colours. 

**Actual result**:
The colours in the resulting image are distorted. It appears as if red and blue are swapped. 

**System details**:
openFrameworks v0.11.0
MacOS 10.14.6, Xcode 10.3

Note that I have tested this issue in v0.9.8 and it works fine in that version.

For more details, see: https://forum.openframeworks.cc/t/ofimage-grabscreen-distorting-colours/34318

**Comment by ofTheo** [comment]
I can reproduce this, even without the resize.

**Comment by ofTheo** [comment]
Note: Saving with "png" the colors look correct. 
But saving to "jpg" the colors get swapped. 

I think the issue is here:
https://github.com/openframeworks/openFrameworks/blob/patch-release/libs/openFrameworks/graphics/ofImage.cpp#L365-L367

the pixels type allocated by ofImage::grabScreen is `OF_PIXELS_BGRA`
In the lines above if you save to jpg the call to `setNumChannels(3)` assumes you are going from RGBA to RGB. Not BGRA to RGB, hence the channels get swapped. 

@jberghold if you change that check in ofImage to:

```
	if(fif==FIF_JPEG && (_pix.getNumChannels()==4 || _pix.getBitsPerChannel() > 8)){
		ofPixels pix3 = _pix;
        if( _pix.getPixelFormat() == OF_PIXELS_BGRA){
            pix3.swapRgb();
        }
        pix3.setNumChannels(3);
		return saveImage(pix3,_fileName,qualityLevel);
	}
``` 

Does it fix it for you?

**Comment by ofTheo** [comment]
Ah I also see the resize issue. 
I think both of these are related to assumptions being made when doing some operations that 3 channels = RGB and 4 channels = RGBA. 

This is not super elegant but should fix the resize issue. 

I think a better approach would either do these checks at lower levels so `setNumChannels(3)` is a little smarter or after `putBmpIntoPixels` you can say with pixel format it is without RGBA being assumed. That would avoid the need for swapRgb being called twice. 


```
//----------------------------------------------------
template<typename PixelType>
void ofImage_<PixelType>::resizePixels(ofPixels_<PixelType> &pix, int newWidth, int newHeight){
    
    //go from BGR order to RGB
    bool bNeedsRGBSwap = (pix.getPixelFormat() == OF_PIXELS_BGRA || pix.getPixelFormat() == OF_PIXELS_BGR );
    if( bNeedsRGBSwap ){
        pix.swapRgb();
    }
    
	FIBITMAP * bmp					= getBmpFromPixels(pix);
	FIBITMAP * convertedBmp			= nullptr;
    
	convertedBmp = FreeImage_Rescale(bmp, newWidth, newHeight, FILTER_BICUBIC);
    putBmpIntoPixels(convertedBmp, pix, false);
    
    //go from RGB order to BGR
    bool bNeedsRGBSwap = (pix.getPixelFormat() == OF_PIXELS_BGRA || pix.getPixelFormat() == OF_PIXELS_BGR );
    if( bNeedsRGBSwap ){
        pix.swapRgb();
    }
    
	if (bmp != nullptr)				FreeImage_Unload(bmp);
	if (convertedBmp != nullptr)		FreeImage_Unload(convertedBmp);
}
```

**Comment by jberghold** [comment]
> @jberghold if you change that check in ofImage to:
> 
> ```
> if(fif==FIF_JPEG && (_pix.getNumChannels()==4 || _pix.getBitsPerChannel() > 8)){
> 	ofPixels pix3 = _pix;
>         if( _pix.getPixelFormat() == OF_PIXELS_BGRA){
>             pix3.swapRgb();
>         }
>         pix3.setNumChannels(3);
> 	return saveImage(pix3,_fileName,qualityLevel);
> }
> ```
> 
> Does it fix it for you?

I tried this and it doesn't fix the issue for me. At this point in my code, `getPixelFormat()` is returning `OF_PIXELS_RGBA`, so `pix3.swapRgb()` never gets called.

However, when I try your second solution it does work, but only if I comment out the second call to `pix.swapRgb()`. 

So, what I have now that works for me is:
```
//----------------------------------------------------
template<typename PixelType>
void ofImage_<PixelType>::resizePixels(ofPixels_<PixelType> &pix, int newWidth, int newHeight){
    
    //go from BGR order to RGB
    bool bNeedsRGBSwap = (pix.getPixelFormat() == OF_PIXELS_BGRA || pix.getPixelFormat() == OF_PIXELS_BGR );
    if( bNeedsRGBSwap ){
        pix.swapRgb();
    }
    
	FIBITMAP * bmp					= getBmpFromPixels(pix);
	FIBITMAP * convertedBmp			= nullptr;
    
	convertedBmp = FreeImage_Rescale(bmp, newWidth, newHeight, FILTER_BICUBIC);
        putBmpIntoPixels(convertedBmp, pix, false);
    
	if (bmp != nullptr)				FreeImage_Unload(bmp);
	if (convertedBmp != nullptr)		FreeImage_Unload(convertedBmp);
}
```

Thanks so much @ofTheo for looking into this!

**Comment by oxillo** [comment]
For the color problem, there may be 2 causes : 
  - grabscreen returning RGBA pixels in OpenGL ES and BGRA pixels in OpenGL 
  - FreeImage requesting RGBA or BGRA depending on OS endianness ([check this answer](https://stackoverflow.com/a/31124181) )

**Comment by ofTheo** [comment]
Okay I think I have a fix in #6670 that accounts for the above issue and a couple of others where ofImage assumes RGB or RGBA. 

If it's helpful here is a test app. 
All images should be a red, green, blue circle on a yellow background. 

```
ofImage img;
//--------------------------------------------------------------
void ofApp::draw(){
    ofBackground(255, 255, 0);

    ofSetColor(255,0,0);
    ofDrawCircle(200, 200, 50);

    ofSetColor(0,255,0);
    ofDrawCircle(400, 200, 50);

    ofSetColor(0,0,255);
    ofDrawCircle(600, 200, 50);

    if( ofGetKeyPressed(' ') ){
        //test grab screen ( BGRA default ) to jpg
        img.clear(); 
        img.grabScreen(0, 0, ofGetWidth(), ofGetHeight());
        
        //uncomment to test RGBA
//        auto pix = img.getPixels();
//        pix.swapRgb();
//        img.setFromPixels(pix);
        
        cout << "1 - image format is " << (int)img.getPixels().getPixelFormat() << endl;
        img.save("test.jpg");
        cout << "1 jpg- image format is " << (int)img.getPixels().getPixelFormat() << endl;
        ofSystem("open "  + ofToDataPath("test.jpg"));
        img.resize(ofGetWidth()/2, ofGetHeight()/2);
        cout << "1 jpg - image format is " << (int)img.getPixels().getPixelFormat() << endl;

        //test grab screen ( BGRA default  ) to png
        img.clear();
        img.grabScreen(0, 0, ofGetWidth(), ofGetHeight());        
        cout << "2 - image format is " << (int)img.getPixels().getPixelFormat() << endl;
        img.save("test.png");
        cout << "2 png - image format is " << (int)img.getPixels().getPixelFormat() << endl;
        ofSystem("open "  + ofToDataPath("test.png"));
        img.resize(ofGetWidth()/2, ofGetHeight()/2);
        cout << "2 png - image format is " << (int)img.getPixels().getPixelFormat() << endl;

        //test dropping alpha channel ( was broken before ) 
        img.setImageType(OF_IMAGE_COLOR);
        cout << "3 jpg - image format is " << (int)img.getPixels().getPixelFormat() << endl;
        img.save("test2.jpg");
        ofSystem("open "  + ofToDataPath("test2.jpg"));
    }

    if( img.isAllocated() ){
        ofSetColor(255);
        img.draw(0, 0);
        
        ofSetColor(0);
        ofDrawBitmapString("captured image", 20, 20);
    }
    
}
```

Before the PR:

<img width="1859" alt="image" src="https://user-images.githubusercontent.com/144000/106046558-46422400-6097-11eb-8585-93d5bdd6b05f.png">


After the PR:

<img width="1579" alt="image" src="https://user-images.githubusercontent.com/144000/106046691-725da500-6097-11eb-864a-cdcd1cfbdf49.png">

**Comment by jberghold** [comment]
Thank you @ofTheo! I've tested the latest nightly build ("of_v20210224_osx_nightly.zip") and the problem is fixed for me.

**Comment by ofTheo** [comment]
Awesome.👍
Thanks for reporting it and confirming too!
