### ISSUE TITLE
[macOS] Xcode "Clean build folder..." aka <cmd-shift-K> removes bin/data directory

### ISSUE THREAD

**Issue by artificiel** [openframeworks/openFrameworks#8276]
it that the new expected behaviour?

macOS14.4 with of-git 20250222 and project made with PG 0.67.0 (20250115)

**Comment by ofTheo** [comment]
100% not! 
I think maybe there is a mistake setting the build folder to bin/ 

cc @dimitre @danoli3

**Comment by dimitre** [comment]
Awful issue
My guess it is related to templates, like a sister issue of this one
https://github.com/openframeworks/openFrameworks/issues/8268

I'm not touching templates I'm not able to understand how they work right now.

**Comment by ofTheo** [comment]
Looking into this and #8268 and the suggestion in #8268 doesn't address/fix either issue. 
Also if you look at the GIt Blame those changes have been around for 4+ months at this point. 

https://github.com/openframeworks/openFrameworks/blame/master/libs/openFrameworksCompiled/project/osx/CoreOF.xcconfig 

`CONFIGURATION_BUILD_DIR = $(SRCROOT)/bin/`

has been around since 0.12.0. 

In fact testing an 0.12.0 project it has an exact same setting for CONFIGURATION_BUILD_DIR and DerrivedData. 
The only difference is that clean in 0.12.0 results in "Clean Failed" so maybe something got fixed in the nightly making clean work again and now its trashing bin/ successfully where as before it failed. 

ie: this is not really a new bug, but exposing a very old bug now that clean is actually working.

**Comment by ofTheo** [comment]
The closest thing I have found to a fix is if we comment out 
`CONFIGURATION_BUILD_DIR = $(SRCROOT)/bin/` 

And use:
`BUILD_DIR = ${PROJECT_DIR}/bin` 

But this has the downside of building this way: 

<img width="417" alt="Image" src="https://github.com/user-attachments/assets/a299de7f-cb29-4431-81a0-4e3a00f9dc5c" />

If there is a way to stop Xcode creating the Debug/ and Release/ subfolders we should have a working fix. 
Cleaning when `BUILD_DIR = ${PROJECT_DIR}/bin` doesn't trash the data folder.

**Comment by danoli3** [comment]
The whole setting the configuration dir completely broke everything

**Comment by danoli3** [comment]
Best to actually used derived data as default, (normal Xcode build locations) and rsync /data to the binary there, copy the final .app to the bin folder as last pass for OSX if developer wants to run it directly or distribute 

for other platforms automatically goes into the derived data folder

**Comment by danoli3** [comment]
I'll fix this now

**Comment by danoli3** [comment]
Fixed https://github.com/openframeworks/openFrameworks/pull/8277

**Comment by artificiel** [comment]
same behaviour:

1. quit/restart PG 0.67.0 and point to fresh git clone `a0707890270ed8bc5e6b33fd9f0485496726beb9`
2. generate new project from OS X (Xcode) template, outside OF folder to ensure absolute OF_PATH
3. open in IDE
4. clean -> failed
5. build
6. clean -> success but bin/ disappears
7. PG update -> re-creates empty bin/data/.gitkeep
8. build
9. clean -> success but bin/ disappears

[Project.xcconfig.zip](https://github.com/user-attachments/files/18928900/Project.xcconfig.zip)

**Comment by danoli3** [comment]
confirmed clean is still messed up a stray BUILD_TARGET_DIR remains

**Comment by danoli3** [comment]
@artificiel fixed https://github.com/openframeworks/openFrameworks/pull/8278

**Comment by ofTheo** [comment]
@danoli3 can you point to what in #8278 fixes the issue?

**Comment by danoli3** [comment]
Ah the app had an app inside it! copy folder depth - fixed 

arching probably related to this build setting set as well:

SKIP_INSTALL = NO

**Comment by danoli3** [comment]
@artificiel should be all fixed now but yes it will run the debug macOS from the derived locations (as default). 
makefile works as normal
Xcode arching works
bin/*.app runs and can be packaged etc

**Comment by dimitre** [comment]
Fantastic 
I've noticed if you compile assimp3DModelLoaderExample assimp.a gets bundled inside the .app folder also

**Comment by danoli3** [comment]
@dimitre probably the copy files not needed for xcframeworks.

<img width="615" alt="Image" src="https://github.com/user-attachments/assets/cedf46fd-5fad-4a21-98a0-a16cc448017e" />

**Comment by ofTheo** [comment]
Some issues still unfortunately: 
- running app from bin/ folder still doesn't work ( at least with the nightly from Feb 25 )
- the current solution ends up causing duplication of data/ folder which could be large for some projects. 

The second is less of an issue for smaller projects, but I think ideally we would want a solution that preserves the old behavior and avoids a copy. 

Going to leave open to see if we can get a 'perfect' fix :)

**Comment by danoli3** [comment]
If you don't want copy just use embedded data folder just like you need for a release anyway.
It's not on by default since data folder is better next to app. 

For a better solution we might need to get Apple developer to check our use case

This is protocol for other Apple targets.

Derived Data use is standard as it's then cleanable by Xcode systems / external clean up cache

Binary depth maybe missed on the nightly that patch. If it's not runnable, check if there's an app in the app. (Show contents)

**Comment by artificiel** [comment]
I'm not sure I understand what you are suggesting: that `bin/` is not anymore a viable destination for built apps? 

also as reported above the Archive/distribute functions to the App Store are not appearing with signed apps as they did before (same as my screenshots above). I presume Xcode works from the `DerivedData` anyway for these? 

another observation: in the case of signed apps, the `_CodeSignature` within the `DerivedData` app is not copied in the `bin/`app. otherwise the structure seems OK (previously the app was broken icon; now it's OF icon, but can't launch, with no crashlog).

<img width="1282" alt="Image" src="https://github.com/user-attachments/assets/7f19d320-4cb9-4668-a242-39c511ad63e1" />

**Comment by danoli3** [comment]
this is so bizarre, it was working perfectly fine from copied app just yesterday but now the universe has made the signing problem appear.

make - works for app in location

all of the variables Xcode exposes for us to set BINARY location all add parent folder to the Clean... so we will lose bin/data or not able to clean the project. Xcode 14 + issue 
```TARGET_BUILD_DIR```
```BUILD_DIR```
```INSTALL_DIR```
```CONFIGURATION_BUILD_DIR```

**Comment by danoli3** [comment]
Okay just added a code sign to the specified identity, by default (with none set its run locally "-")
Should solve the problems

**Comment by artificiel** [comment]
OK code signature is now there in the bin/ copy, but still no luck with archive/distribute (nor running from bin/).

are you in a position to try the archive /distribute process? or minimally the "validate content" step?

another observation: when things used to work the Xcode archives were of type "macOS App Archive"; now they are of type "Generic Xcode Archive", and the buttons have different labels:

GOOD:
<img width="318" alt="Image" src="https://github.com/user-attachments/assets/de53a407-acb6-46a3-8f8e-ebcde276d8ba" />

NOT GOOD:
<img width="237" alt="Image" src="https://github.com/user-attachments/assets/21d20d4c-f26b-4c73-9fea-5e1069074548" />

**Comment by danoli3** [comment]
run clean and then run the bin/*.app it will run now

Archiving is broken, not sure how long ago thats been like that, likely one of the settings in the xconfig or custom plist as the one archived is some weird one without the data

**Comment by danoli3** [comment]
okay v12.0.0 archiving works. plist looks like this:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>ApplicationProperties</key>
	<dict>
		<key>ApplicationPath</key>
		<string>Applications/mySketchDebug.app</string>
		<key>Architectures</key>
		<array>
			<string>x86_64</string>
			<string>arm64</string>
		</array>
		<key>CFBundleIdentifier</key>
		<string>cc.openFrameworks.mySketch</string>
		<key>CFBundleShortVersionString</key>
		<string>1.0</string>
		<key>CFBundleVersion</key>
		<string>1.0</string>
		<key>SigningIdentity</key>
		<string></string>
		<key>Team</key>
		<string></string>
	</dict>
	<key>ArchiveVersion</key>
	<integer>2</integer>
	<key>CreationDate</key>
	<date>2025-02-26T13:29:09Z</date>
	<key>Name</key>
	<string>mySketch Debug</string>
	<key>SchemeName</key>
	<string>mySketch Debug</string>
</dict>
</plist>

```

plist in master (recent) when archiving:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>ArchiveVersion</key>
	<integer>2</integer>
	<key>CreationDate</key>
	<date>2025-02-26T13:31:59Z</date>
	<key>Name</key>
	<string>mySketch4 Debug</string>
	<key>SchemeName</key>
	<string>mySketch4 Debug</string>
</dict>
</plist>

```

here is the problem... why though

**Comment by NickHardeman** [comment]
> The closest thing I have found to a fix is if we comment out `CONFIGURATION_BUILD_DIR = $(SRCROOT)/bin/`
> 
> And use: `BUILD_DIR = ${PROJECT_DIR}/bin`
> 
> But this has the downside of building this way:
> 
> <img alt="Image" width="417" src="https://private-user-images.githubusercontent.com/144000/415943332-a299de7f-cb29-4431-81a0-4e3a00f9dc5c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDA1ODQ2OTMsIm5iZiI6MTc0MDU4NDM5MywicGF0aCI6Ii8xNDQwMDAvNDE1OTQzMzMyLWEyOTlkZTdmLWNiMjktNDQzMS04MWEwLTRlM2EwMGY5ZGM1Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDIyNlQxNTM5NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZjBiNmIzMzE3ZDZjNzU5ZGI0YzMyMWFhODQxMWI0ZjQyNGUxY2MxN2Y3NGQwOWQ3MzQ2MTRlNTRlN2FjOGU1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.FTBdWsSjjTKlmIPBPhbHNWk4ytSaGZvUzLKmQiZmtuw">
> If there is a way to stop Xcode creating the Debug/ and Release/ subfolders we should have a working fix. Cleaning when `BUILD_DIR = ${PROJECT_DIR}/bin` doesn't trash the data folder.

If I set the following in Project.xcconfig 
```
TARGET_BUILD_DIR = ${PROJECT_DIR}/bin
BUILT_PRODUCTS_DIR = ${PROJECT_DIR}/bin
```

Comment out the `copy_binary` function call in `scripts/osx/xcode_project.sh`

And set the following in the Run Script Build Phase
```
"$OF_PATH/scripts/osx/xcode_project.sh"
find ${PROJECT_DIR}/bin -type d -name "*" -exec xattr -w com.apple.xcode.CreatedByBuildSystem false "{}" \;
```

It seems to work as before, the clean fails since it doesn't remove the bin/ folder. But the clean does remove items inside build/

**Comment by danoli3** [comment]
> It seems to work as before, the clean fails since it doesn't remove the bin/ folder. But the clean does remove items inside build/

still if any addons are used include and .a copied to this build dir  - by Xcode internally 

<img width="418" alt="Image" src="https://github.com/user-attachments/assets/fea62b79-5fe6-4910-b255-b6dda0053038" />

the archiving still broken we know this must be therefore just a info plist change issue

**Comment by dimitre** [comment]
I'm making a test separately to see if it is something else. Can you compile universal (any mac) @danoli3 ?
to archive and send to app store you need to be able to compile universal

**Comment by danoli3** [comment]
its something plist related see https://github.com/openframeworks/openFrameworks/issues/8276#issuecomment-2684970194 look for plist settings. 

Compare to https://github.com/openframeworks/openFrameworks/releases/download/0.12.0/of_v0.12.0_osx_release.zip

**Comment by artificiel** [comment]
ok i report some success — the archive problem not related to the xcodeproj or info/capabilities/settings.

it is caused by the bin/data folder that gets copied in Products/Applications — that messes up the Archive. activating the `OF_BUNDLE_DATA_FOLDER = 1` moves the data dir within the `.app/Contents/Resources`, and that enables the Archive to be exported as a macOS app.

so I guess something changed in the default (unbundled) case of the data dir management. the default case should work...

**Comment by danoli3** [comment]
we should really have a Debug / Release / AppStore targets where AppStore auto bundles 
If archive it runs AppStore @dimitre didn't you set that up ages ago ?

**Comment by artificiel** [comment]
to be precise the problem is not that `bin/data` is not bundled, but that it is copied in `Products/Applications`

**Comment by danoli3** [comment]
<img width="1169" alt="Image" src="https://github.com/user-attachments/assets/b8fea56e-8e17-4c2d-a457-ed4ea772fb46" />

nah Products/Applications is correct ^ this is from v12 where it worked to validate, again its just the plist describing it that is broken for the package archive it seems

**Comment by danoli3** [comment]
<img width="1137" alt="Image" src="https://github.com/user-attachments/assets/eae0d8cc-9292-44b2-940a-58ab8509d138" />

**Comment by danoli3** [comment]
<img width="740" alt="Image" src="https://github.com/user-attachments/assets/619ab42d-e645-4edb-b62a-edc80eaf2c19" /> looks good at v12 with that plist

**Comment by danoli3** [comment]
oh yeah so you think maybe its just cause the data folder is copied into there that it breaks ? okay let me check

**Comment by danoli3** [comment]
you got it! nice one @artificiel

**Comment by dimitre** [comment]
@danoli3 we removed Appstore configuration. it was really confusing and needed 15 steps more to work.
now it is working much better to archive and submit apps
it is a pity xcconfig file format doesnt support a selector like this:
```
COPY_PHASE_STRIP[config=Archive] = YES
```

**Comment by artificiel** [comment]
OK closing this as as the title (disappearing bin/data) is solved; it the Archive/Distribute stuff needs touch up it'll be another issue.
